[package]
name = "wireguard-p2p"
version = "0.1.0"
authors = ["Manuel Sch√∂lling <manuel.schoelling@gmx.de>"]

[dependencies]
tokio-core = "*"
futures = "*"
#stun3489 = "0.2.0"
stun3489 = { path = "../stun3489" }
dbus-tokio = "0.1.1"
dbus = "0.5.3"
byteorder = "1.0.0"
log = "*"
env_logger = "0.4.3"
rust-ini = "*"
sodiumoxide = "*"
base64 = "0.6.0"
error-chain = "*"
docopt = "*"

